services:
  pickems-db:
    image: postgres:17.4-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  # pickems:
  #   container_name: pickems
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   expose:
  #     - "80"

volumes:
  pgdata:
